title = "pracht"
baseURL = "https://pracht.report/"
languageCode = "de-de"
defaultContentLanguage = "de"
paginate = 15
anonymize = true

[minify]
  disableCSS = false
  disableJS = false
  disableHTML = false
  disableXML = false
  minifyOutput = true

[imaging]
  quality = 85
  resampleFilter = "Lanczos"

[params]
  dateFormat = "02.01.2006"
  description = "die meinung, ein Blog über alles."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "24h"

[taxonomies]
  category = "themen"

[build]
  writeStats = true
  noJSConfigInAssets = true

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^GO_']

[build.processing]
  [build.processing.css]
    bundle = true
    minify = true
  
  [build.processing.js]
    bundle = true
    minify = true