title = "pracht"
baseURL = "https://pracht.report/"
languageCode = "de-de"
paginate = 10

[minify]
  disableCSS = false
  disableJS = false
  disableHTML = false
  disableXML = false
  minifyOutput = true

[imaging]
  quality = 85
  resampleFilter = "Lanczos"

[params]
  dateFormat = "02.01.2006"
  description = "die meinung, ein Blog über alles."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[assetDirs]
  cssDir = "static/styles"
  jsDir = "static/js"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "24h"

[taxonomies]
  category = "themen"

[build]
  writeStats = true